### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by p4olo-90** [gius-italy/dmg-lib-downloader#1]
Hi, thank you for your job!
I am trying to use your downloader, using the link in example but nothing appear in my directory.

Can you confirm that the code still work ?

Thank you

**Comment by glumia** [comment]
Hi Paolo! It seems that something had changed on dmg-lib and the script had stopped working. I've just pushed a commit to fix it. Let me know if you should still not be able to use it :)

**Comment by p4olo-90** [comment]
Hi Glumia! thank you for your support! I am trying to use your new code but something goes wrong " invalid syntax". Maybe it's my fault but I am not sure. Can you help me?

In attachment the error:

![Inavlid Syntax](https://github.com/glumia/dmg-lib-downloader/assets/13084511/b0b83797-192d-4510-ad05-c3fcdaeacef2)

**Comment by p4olo-90** [comment]
Hi Glumia! All Works Fine!  Following the code that I use:

```
import re
import sys
from urllib.request import urlretrieve

import requests

url_libro=input("Inserisci l'url del libro che vuoi scaricare nuovo: ")
book_id=url_libro.split('=')[-1]

with requests.session() as session:

    r=session.get(url_libro)

    # r = session.get(sys.argv[1])

    # one shouldn't use regexes to parse html, but in this case they are good enough
    img_list = [
        s.strip('" ')
        for s in re.search(r"Array\(([^)]+)\)", r.text).groups()[0].split(",")
    ]
    book_path = re.search(r'Bilderverzeichnis += +"([^"]+)"', r.text).groups()[0]

    print("Downloading...")
    for img in img_list:
        print(img)
        path = "https://www.dmg-lib.org" + book_path + "/thumbs/1_0002/" + img
        urlretrieve(
            "https://www.dmg-lib.org" + book_path + "/thumbs/1_0002/" + img, img
        )

    print("Download completed.")
```
